### ISSUE TITLE
This is great!

### ISSUE THREAD

**Issue by bkvargyas** [sbabcock23/hass-tryfi#12]
I can't wait to try this!    I've been wanting to order a GPS collar for our dog, and as soon as this popped up on HACS, it's a win-win!   Ordered today! --- I know this is for reporting issues, but hey, I wanted to congratulate you on the the work for the integration.   Feel free to delete.

**Comment by sbabcock23** [comment]
Let me know if you have any feedback! Have fun with the new collar @bkvargyas

**Comment by sdellysse** [comment]
Didn't want to spam anywhere else but also wanted to say, this is awesome! Thank you so much for making this integration!
