### ISSUE TITLE
Multiple Bases

### ISSUE THREAD

**Issue by Leko1933** [sbabcock23/hass-tryfi#13]
Installed via HACS, then when configuring the integration it only saw 1 of two bases. Went checked everything out all seemed to be good except the only seeing 1 of 2 bases. Tried reload on the integration and it added the 2nd bases, but now the 1st base entity shows as unavailable.

Thank you for developing this! If there is anything I can do to support the project please let me know!

**Comment by sbabcock23** [comment]
Hi @Leko1933  - I've created version 0.0.3 that I believe fixes the issue and also adds some additional logging. Give this a try, if it does not work, please enable log level debug in your HA, remove the integration and re-add the integration. I am looking for lines that are like this:
2020-12-28 22:50:33 DEBUG (MainThread) [custom_components.tryfi.sensor] Adding Base: Last Updated - 2020-12-28 22:50:33.444726 - Base ID: FB19M56049 Name: Main Floor Base Online Status: True Wifi Network: ChelseaFC-Infra

**Comment by Leko1933** [comment]
Just updated and it looks like you got it! Both bases are showing same last updated now. Thank you!

**Comment by sbabcock23** [comment]
Awesome. Thanks for confirming!
