### ISSUE TITLE
TryFi doesn't show up on hass integrations after hacs installation

### ISSUE THREAD

**Issue by lazynomad** [sbabcock23/hass-tryfi#16]
Can successfully add HACS TryFi repository and install it.
However, following the documentation, I cannot find "TryFi" when searched in Configuration -> Integrations.
Am I doing something wrong or is this a bug ?

**Note**: I installed the version 0.0.3
Hassio version is 2020.12.0

**Comment by stonesrose** [comment]
I'm having the same issue.
