### ISSUE TITLE
Eating FI battery?

### ISSUE THREAD

**Issue by lmerriam** [sbabcock23/hass-tryfi#34]
Since I installed this integration with the default polling rate of 10 my Fi module is going through battery ~3x faster than normal. Is it possible that asking the Fi service for location causes it to actively ping the device for location, rather than just returning the last location it had recorded?

Not sure if there's a feasible solution in any case, but thought I would report it since I haven't seen it in any other tickets. I've changed my polling rate to 300 to see if that reduces the battery burn.

**Comment by sbabcock23** [comment]
Hi @lmerriam ,

I don't think that's the case. I have mine set to 10s without any issues. The only time I see significant decrease in the battery is when the collar is not connected to the base or a phone. However let me know what you find oit!

**Comment by lmerriam** [comment]
The dog in question didn't leave the home network for days during this period due to rainy weather, which is why I thought it was so odd that it was dropping 10% daily for multiple days in a row. Typically it's just a few percent a day even with long walks. That said, there's no way to know exactly what caused it so if you don't think using the integration could cause that behavior then I'm sure it was something else. Closing this ticket
