### ISSUE TITLE
Sleep tracking

### ISSUE THREAD

**Issue by dougtechdude** [sbabcock23/hass-tryfi#36]
Fi has recently introduced Sleep tracking to their ver. 2 dog collars, it would be awesome to see these new stats show up as entities within HA.

In the app you can see stats on your dogs napping, and sleeping habits from the night before, but also: hourly, daily, weekly, and monthly. The app also pinpoints at which point during the night your pup had an interruption (it counts these per night), and was awoken.

More information on the new [Sleep tracking feature](https://tryfi.com/sleeptracking/) from Fi.

**Comment by sbabcock23** [comment]
@dougtechdude - there has been a recent enhancement to include the sleep and nap metrics. This was updated in v0.0.14.
