### ISSUE TITLE
Integration loading fine but only finding 2 entities.

### ISSUE THREAD

**Issue by Collin98783** [sbabcock23/hass-tryfi#39]
I was able to get the TryFi integration loaded into HA following the instructions step by step but its only finding 2 entities,(Light.pet_collar_Light) (Select.pet_lost_mode). and even though HA "found" them, there state is unavailable and cant be used in any way. ive restarted HA, Tried the manual install method, Re-loaded the TryFi Application on my phone but all  same results. 
not sure if this is a bug or something im missing? im using the most up to date version of Home Assistant, HACS and the TryFI integration. any help would be great

EDIT: i saw something about Pytryfi in another issue fourm. not sure if this is something i need to make this work or not, didnt see anything in the instructions about it.  
![20220327_212426](https://user-images.githubusercontent.com/102104628/160311558-7ad22b88-7192-41f9-bec0-8ceb47a53ff3.jpg)
![20220327_212438](https://user-images.githubusercontent.com/102104628/160311566-dcf3be47-0a92-431c-809f-6d4fb3130457.jpg)
![20220327_212456](https://user-images.githubusercontent.com/102104628/160311580-cef7e724-220f-4d47-9951-0e4813cc8094.jpg)
!

**Comment by estiens** [comment]
Same here. Gonna see after a day or two the other ones pop up!

**Comment by estiens** [comment]
@Collin98783 - if you installed from HACS pytryfi should be installed automatically

**Comment by estiens** [comment]
The rest of mine came in after about an hour and another restart of core. I did make sure my app on my phone was closed at the time, but doesn't seem to have a problem both being connected now...

**Comment by sbabcock23** [comment]
Hi @Collin98783 ,

Are you still having this issue? If you can enable debugging in HA, I would be interested in the TryFi debug logs.

Thanks!

**Comment by Apadgett879** [comment]
> Hi @Collin98783 ,
> 
> Are you still having this issue? If you can enable debugging in HA, I would be interested in the TryFi debug logs.
> 
> Thanks!

Hello, I also get this issue actively, What information would you like?

**Comment by Apadgett879** [comment]
@sbabcock23 Its been a few days for me, and I also only see 1 device and 2 entities as well.
What information can I give you to assist with troubleshooting?

**Comment by sbabcock23** [comment]
Hi @Apadgett879 ,

Can you enable debug mode in HA and then restart HA? During the restart there should be several debug statements that have tryfi in them, you can share all of these. Please just cross check that there isn't any sensitive/personal data before you share (e.g. firstname, lastname, etc.).

**Comment by Apadgett879** [comment]
@sbabcock23 

It was a lot of info so I made a pastebin

https://pastebin.com/EnVnrhu6

it appears to loop this error over and over

I have a unredacted version if you need the additional Info.

**Comment by eternistarr** [comment]
I'm having the same issue. Would my logs be helpful as well?

**Comment by sbabcock23** [comment]
Yes @eternistarr it would help as well. Especially during the issue.

**Comment by eternistarr** [comment]
> Yes @eternistarr it would help as well. Especially during the issue.

Sorry thought this would be easier but I'm not seeing a built in way to get what you need and I'm not finding clear documentation on how to get it.

**Comment by Apadgett879** [comment]
@eternistarr 
I installed the log viewer addon
and added logger to my yaml file then rebooted

**Comment by eternistarr** [comment]
`2022-04-30 15:44:47 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 137, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 328, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 994, in state
    if (is_on := self.is_on) is None:
  File "/config/custom_components/tryfi/light.py", line 74, in is_on
    return bool(self.pet.device.ledOn)
  File "/usr/local/lib/python3.9/site-packages/pytryfi/fiDevice.py", line 60, in ledOn
    return self._ledOn
AttributeError: 'FiDevice' object has no attribute '_ledOn'
Connected`

**Comment by sbabcock23** [comment]
@eternistarr , can you share other references to tryfi in your logs? I'm looking for the api responses.

**Comment by Apadgett879** [comment]
@sbabcock23 did mine contain the needed info?

**Comment by sbabcock23** [comment]
> @sbabcock23 did mine contain the needed info?

It had the info in it. I took a quick glance I didn't see any errors but I'll take a closer look at it shortly.

**Comment by Apadgett879** [comment]
@sbabcock23 the error was at the very end, seemed to be a python error

**Comment by eternistarr** [comment]
https://pastebin.pl/view/cefb4afd

**Comment by sbabcock23** [comment]
Thanks @eternistarr , this helps but it doesn't have the debug logs. Can you set the log level to debug and restart HA so I can see everything?

**Comment by eternistarr** [comment]
> Thanks @eternistarr , this helps but it doesn't have the debug logs. Can you set the log level to debug and restart HA so I can see everything?

If I knew how. I've been trying to find some article to tell me how but only find vsocde stuff and I couldn't get it to connect

**Comment by sbabcock23** [comment]
Hi @eternistarr ,

You can set the below in configuration.yaml

logger:
  default: debug

**Comment by Apadgett879** [comment]
@eternistarr 
use the above change,
use the terminal add on to make it easier
use the log viewer add on

**Comment by eternistarr** [comment]
https://pastebin.pl/view/e684e127
Any better?

**Comment by sbabcock23** [comment]
Thank you @eternistarr and @Apadgett879 , I believe I found the issue based on what you provided. Please give the latest version of hass-tryfi a go. It should be version 0.0.11

**Comment by Apadgett879** [comment]
@sbabcock23 I can confirm this resolved my issue. Thank you!

**Comment by eternistarr** [comment]
> Thank you @eternistarr and @Apadgett879 , I believe I found the issue based on what you provided. Please give the latest version of hass-tryfi a go. It should be version 0.0.11

Thank You, This fixed it!

**Comment by Collin98783** [comment]
Hello! I know I haven't been active on this thread since my issue was posted. Just wanted to say since the latest TryFi update my issue has been resolved!!! Thanks for a great integration! I look forward to seeing what other great features get added!
