### ISSUE TITLE
Intergration no longer working

### ISSUE THREAD

**Issue by Apadgett879** [sbabcock23/hass-tryfi#44]
After the .12 update it appears the intergration no longer works at all.
I can not even remove and set it up again as I get an error that the intergration does not support configuration via the UI.

**Comment by sbabcock23** [comment]
Hi @Apadgett879 ,

Can you share the debug logs? The overall change was very minor so I'm not sure what the issue is. 

Thanks!

**Comment by Apadgett879** [comment]
@sbabcock23 I must apologize, it seems I managed to get a corrupted download, after updating back to .12 from .10 it all seems to work.

Please feel free to close this issue.

**Comment by sbabcock23** [comment]
No worries thanks @Apadgett879 for confirming.

**Comment by Apadgett879** [comment]
I sure will when I get home tonight, I rolled back to .10 for now, and it
is working.
